export const config: IConfig = {
  docWidth: 816,
  docHeight: 1056,
  rulerOffset: 12,
  editor: {
    excludeKeys: new Set([
      "Enter",
      "ShiftRight",
      "ShiftLeft",
      "CapsLock",
      "ControlRight",
      "ControlLeft",
      "AltRight",
      "AltLeft",
      "Escape",
      "Insert",
    ]),
    preventKeys: new Set(["Space", "Tab"]),
  },
  customFonts: [
    "open-sans",
    "barlow-condensed",
    "caveat",
    "crimson-text",
    "dancing-script",
    "inter",
    "lato",
    "lobster",
    "montserrat",
    "nunito-sans",
    "oswald",
    "pacifico",
    "poppins",
    "quicksand",
    "roboto",
    "roboto-mono",
    "rubik",
    "ubuntu",
  ],
  fonts: {
    "open-sans": "Open Sans",
    "barlow-condensed": "Barlow Condensed",
    caveat: "Caveat",
    "crimson-text": "Crimson Text",
    "dancing-script": "Dancing Script",
    inter: "Inter",
    lato: "Lato",
    lobster: "Lobster",
    montserrat: "Montserrat",
    "nunito-sans": "Nunito Sans",
    oswald: "Oswald",
    pacifico: "Pacifico",
    poppins: "Poppins",
    quicksand: "Quicksand",
    roboto: "Roboto",
    "roboto-mono": "Roboto Mono",
    rubik: "Rubik",
    ubuntu: "Ubuntu",
  },
  scale: [0.5, 0.75, 1, 1.25, 1.5, 1.75, 2],
  fontSizes: [
    "6px",
    "8px",
    "10",
    "12px",
    "14px",
    "16px",
    "18px",
    "20px",
    "22px",
    "24px",
    "26px",
    "28px",
    "30px",
    "32px",
    "34px",
    "36px",
  ],
  defaultFont: "open-sans",
  defaultFontSize: "16px",
};
